name: create release digests

on:
  release:
    types: [ published]
    branches: [ master ]
  
jobs:
  once:
    name: Creating digests
    runs-on: ubuntu-20.04
    steps:
      - name: Digest
        uses: MCJack123/ghaction-generate-release-hashes@v1
        with:
          hash-type: sha1
          file-name: kubescape-release-digests
